### ISSUE TITLE
[Lab] Update links for blog entrance

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-lab#10]
### Tasks
- [x] change footer link of `medium` to ours blog page
- [x] change our latest blog link of `read more` to our blog page
- [x] change every card's link in our latest blog to it's own page link
- [x] add blog page link into navigation

### References
- `todo`

**Comment by devformatters** [comment]
Close it. Will file a new issue that summarize the following todo.
