### ISSUE TITLE
[Lab] Update copy

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-lab#9]
### Tasks
- [ ] Update 80,000 creators to 100,000 in Matters.news section
- [ ] Update joinus link
- [ ] Fix press coverage links are not matched card contents

### References
- [Slack](https://mattersnews.slack.com/archives/G8877EQMS/p1660035363179949?thread_ts=1649922504.715359&cid=G8877EQMS)

**Comment by devformatters** [comment]
Shipped. Close it.
